/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chat;

import chat_video.Client;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.net.Socket;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.*;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author aatmin
 */
public class Chat_Client extends javax.swing.JFrame{

    ImageIcon i1,i3;
    Image i2;
    
    static Box vertical = Box.createVerticalBox();
    
    static Socket sc,sf;
    static DataInputStream din;
    static DataOutputStream dout;
    
    static ObjectOutputStream out;
    
    Boolean typing;
    
    /**
     * Creates new form Chat_Client
     */
    public Chat_Client() {
        initComponents();
        /*
        Timer t = new Timer(1, (ActionEvent ae) -> {
            if(!typing){
                l4.setText("Active Now");
            }
        });
       
       t.setInitialDelay(2000);*/
       
       i1 = new ImageIcon(ClassLoader.getSystemResource("Chat/icons/3.png"));
       i2 = i1.getImage().getScaledInstance(l1.getWidth(), l1.getHeight(), Image.SCALE_DEFAULT);
       i3 = new ImageIcon(i2);
       l1.setIcon(i3);
       
       i1 = new ImageIcon(ClassLoader.getSystemResource("Chat/icons/2.png"));
       i2 = i1.getImage().getScaledInstance(l2.getWidth(), l2.getHeight(), Image.SCALE_DEFAULT);
       i3 = new ImageIcon(i2);
       l2.setIcon(i3);
       /*
       i1 = new ImageIcon(ClassLoader.getSystemResource("Chat/icons/video.png"));
       i2 = i1.getImage().getScaledInstance(bv.getWidth(), bv.getHeight(), Image.SCALE_DEFAULT);
       i3 = new ImageIcon(i2);
       bv.setIcon(i3);
       
       i1 = new ImageIcon(ClassLoader.getSystemResource("Chat/icons/phone.png"));
       i2 = i1.getImage().getScaledInstance(l6.getWidth(), l6.getHeight(), Image.SCALE_DEFAULT);
       i3 = new ImageIcon(i2);
       l6.setIcon(i3);
       
       i1 = new ImageIcon(ClassLoader.getSystemResource("Chat/icons/3icon.png"));
       i2 = i1.getImage().getScaledInstance(l7.getWidth(), l7.getHeight(), Image.SCALE_DEFAULT);
       i3 = new ImageIcon(i2);
       l7.setIcon(i3);*/
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        ba = new javax.swing.JButton();
        bv = new javax.swing.JButton();
        bf = new javax.swing.JButton();
        t1 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        a1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(254, 254, 254));
        setLocation(new java.awt.Point(1100, 200));
        setUndecorated(true);
        setSize(new java.awt.Dimension(450, 700));

        p1.setBackground(new java.awt.Color(7, 94, 84));
        p1.setLayout(null);

        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        p1.add(l1);
        l1.setBounds(5, 17, 30, 30);
        p1.add(l2);
        l2.setBounds(40, 5, 60, 60);

        l3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(254, 254, 254));
        l3.setText("Bunty");
        p1.add(l3);
        l3.setBounds(110, 15, 100, 18);

        l4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        l4.setForeground(new java.awt.Color(254, 254, 254));
        l4.setText("Active Now");
        p1.add(l4);
        l4.setBounds(110, 35, 100, 20);

        ba.setText("A");
        p1.add(ba);
        ba.setBounds(350, 20, 30, 30);

        bv.setText("V");
        bv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvActionPerformed(evt);
            }
        });
        p1.add(bv);
        bv.setBounds(290, 20, 30, 30);

        bf.setText("F");
        bf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfActionPerformed(evt);
            }
        });
        p1.add(bf);
        bf.setBounds(410, 20, 30, 30);

        t1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N

        b1.setBackground(new java.awt.Color(7, 94, 84));
        b1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        b1.setForeground(new java.awt.Color(254, 254, 254));
        b1.setText("Send");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        a1.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        a1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getAccessibleContext().setAccessibleName("f1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_l1MouseClicked

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        try{
            String out = t1.getText();
            
            JPanel p2 = formatLabel(out);
            
            //a1.setLayout(new BorderLayout());
            
            JPanel right = new JPanel(new BorderLayout());
            right.add(p2, BorderLayout.LINE_END);
            vertical.add(right);
            vertical.add(Box.createVerticalStrut(15));
            
            a1.add(vertical, BorderLayout.PAGE_START);
            
            JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(a1);
            topFrame.validate();
            
            //a1.add(p2);
            dout.writeUTF(out);
            t1.setText("");
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void bfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfActionPerformed
        // TODO add your handling code here:
        
        try {
            JFileChooser ch = new JFileChooser();
            int c = ch.showOpenDialog(this);
            if (c == JFileChooser.APPROVE_OPTION) {
                File f = ch.getSelectedFile();
                FileInputStream in = new FileInputStream(f);
                byte b[] = new byte[in.available()];
                in.read(b);
                Data data = new Data();
                //data.setStatus(jComboBox1.getSelectedItem() + "");
                //data.setName(txtName.getText().trim());
                data.setFile(b);
                out.writeObject(data);
                out.flush();
                //txt.append("Sent a file ..\n");
                System.out.println("Sent a file ...");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_bfActionPerformed

    private void bvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvActionPerformed
        // Video calling code
        Client cv=new Client();
        cv.setVisible(true);
    }//GEN-LAST:event_bvActionPerformed

    public static JPanel formatLabel(String out){
        JPanel p3 = new JPanel();
        p3.setLayout(new BoxLayout(p3, BoxLayout.Y_AXIS));
        
        JLabel l1 = new JLabel("<html><p style = \"width : 150px\">"+out+"</p></html>");
        l1.setFont(new Font("Tahoma", Font.PLAIN, 16));
        l1.setBackground(new Color(37, 211, 102));
        l1.setOpaque(true);
        l1.setBorder(new EmptyBorder(15,15,15,50));
        
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        
        JLabel l2 = new JLabel();
        l2.setText(sdf.format(cal.getTime()));
        
        p3.add(l1);
        p3.add(l2);
        return p3;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat_Client().setVisible(true);
            }
        });
        
        try{
            
            sc = new Socket("127.0.0.1", 6001);
            sf = new Socket("127.0.0.1", 8003);
            din  = new DataInputStream(sc.getInputStream());
            dout = new DataOutputStream(sc.getOutputStream());
            out = new ObjectOutputStream(sf.getOutputStream());
            
            String msginput = "";
            
	    while(true){
                //a1.setLayout(new BorderLayout());
	        msginput = din.readUTF();
            	JPanel p2 = formatLabel(msginput);
                JPanel left = new JPanel(new BorderLayout());
                left.add(p2, BorderLayout.LINE_START);
                
                vertical.add(left);
                vertical.add(Box.createVerticalStrut(15));
                a1.add(vertical, BorderLayout.PAGE_START);
                JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(a1);
                topFrame.validate();
                 
                System.out.println("4");

                
            }
            
        }catch(Exception e){}
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel a1;
    private javax.swing.JButton b1;
    private javax.swing.JButton ba;
    private javax.swing.JButton bf;
    private javax.swing.JButton bv;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JPanel p1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
